import os
import re
import json
import time
import pprint
import string
import requests
import warnings
import multiprocessing

import numpy as np
import pandas as pd

from tqdm import tqdm
from PIL import Image
from io import BytesIO
from google import genai
from bs4 import BeautifulSoup
from newsplease import NewsPlease
from typing import Union, Optional
from datetime import timedelta, datetime
from transformers import AutoFeatureExtractor, AutoModel
from sentence_transformers import SentenceTransformer, util

from selenium import webdriver
from selenium.webdriver.firefox.options import Options

# from serpapi import GoogleSearch  # type: ignore
# import preprocessor as p
# p.set_options(p.OPT.URL, p.OPT.RESERVED, p.OPT.EMOJI, p.OPT.SMILEY)

warnings.filterwarnings('ignore')
os.environ['TOKENIZERS_PARALLELISM'] = 'false'

DIR_PATH = os.path.dirname(os.path.abspath(__file__))


def gemini(api_key: str, prompt: str) -> str:
    """
    Generate response to the prompt from Gemini.

    Parameters
    ----------
    api_key : str
        Genrated API key to Gemini
    prompt : str
        Prompt to be fed into Gemini

    Returns
    -------
    Response from gemini or empty string if response is not available

    Notes
    -----
    Tries two times. If it fails, return empty string.
    """
    max_retries = 2
    curr_tries = 1
    while curr_tries <= max_retries:
        try:
            client = genai.Client(api_key=api_key)

            response = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt,
            )
            return response.text
        except Exception as e:
            print('\t' + str(e))
            curr_tries += 1
            time.sleep(5)
            continue
    return ''


def query_generation(news: dict, llm_key: str) -> str:
    """
    Generate query according to our template. To achieve this, we:
    1. Prepare news data.
    2. Load the prompt template.
    3. Prepare the prompt.
    4. Generate queries with Gemini.

    Parameters
    ----------
    news : dict
        Dictionary contatining information like: ID, category, topics,
        source, headline and text of an article.
    llm_key :
        Generated API key to Gemini.

    Returns
    -------
    response : str
        Query generated by feeding prompt into Gemini.
    """

    def news_prep(news_category: str, news_text: str) -> str:
        """
        Prepare news data
        """
        return f'news category: {news_category}, content: {news_text}'

    news_content = news_prep(news['CATEGORY'], news['TEXT'])

    # Load the prompt template
    prompt_path = os.path.join(DIR_PATH, 'data', 'prompt_query_generation_unimodal.txt')
    with open(prompt_path, 'r') as f:
        prompt_format = f.read()

    prompt = prompt_format.replace('[NEWS_CONTENT]', news_content)
    response = gemini(llm_key, prompt)

    return response


def query_search(api_key: str, search_engine_id: str, news: dict, domain_priority: str) -> dict:
    """
    Perform web search for a news article using Google Programmable Search
    and save/load results to/from local JSON files.

    For each query in the news data:
      1. Preprocess the query.
      2. Generate a path for saving the search results.
      3. Ensure the directory exists.
      4. Load cached search results if available, otherwise perform the search.
      5. Save search results to JSON for future reuse.
      6. Aggregate search results for all queries.

    Parameters
    ----------
    api_key : str
        API key to access Google Programmable Search API.
    search_engine_id : str
        ID of the Google Custom Search Engine.
    news : dict
        Dictionary containing news information. Must include key "queries" which
        contains queries separated by newlines.
    domain_priority : str
        Priority label for the news source (e.g., "High", "Medium", "Low").
        Used for saving search results in a priority-specific file.

    Returns
    -------
    search_results : dict
        Dictionary mapping preprocessed queries to search result data.
        If cached results exist, loads from JSON files; otherwise, results
        are fetched via API and saved locally.
    """

    def google_programmable_search(api_key: str, search_engine_id: str, query: str):
        """
        Get search results of a single query.

        api_key : str
            API key to Google API.
        search_engine_id : str
            ID of Google search engine.
        query : str
            Query to be searched.

        Returns
        -------
        results : dict
            Results of a search in form of dict.
        """
        params = {'key': api_key, 'cx': search_engine_id, 'q': query}
        search = requests.get("https://www.googleapis.com/customsearch/v1", params=params)
        results = search.json()
        return results

    search_results = {}
    queries = news["queries"]
    # No queries, return {}
    if queries in ["NONE", "\"NONE\""]:
        return search_results

    # Otherwise, [query_1, query_2, ...]
    queries = queries.split('\n')
    queries = [q for q in queries if len(q) > 0 and q[0] in ['1', '2', '3']]

    for x, query_x in enumerate(queries):
        qx = ' '.join(query_x.split(' ')[1:])
        qx = qx.translate(str.maketrans('', '', string.punctuation))
        save_file = os.path.join(DIR_PATH, 'data', 'web_search_text', f'{qx}_{domain_priority}.json')

        # Make sure that directory exists
        os.makedirs(os.path.dirname(save_file), exist_ok=True)

        # If the search results have not been saved, do web search. Otherwise, load the search results
        if not os.path.exists(save_file):
            with open(save_file, 'w') as f:
                json.dump({}, f, indent=4)
        with open(save_file, 'r') as f:
            google_programmable_search_outputs = json.load(f)
        if 'items' in google_programmable_search_outputs.keys():
            search_results[qx] = google_programmable_search_outputs
        else:
            output = google_programmable_search(api_key, search_engine_id, qx)
            print("OUTPUT:", output)
            print("\t(sent 1 request to google programmable search)")
            if 'items' in output.keys():
                search_results[qx] = output
            google_programmable_search_outputs = output
            with open(save_file, 'w') as f:
                json.dump(google_programmable_search_outputs, f, indent=4)
    return search_results


def filter_search_results_by_domain(search_results: dict, domain_priority: str, page_num: Optional[int] = None) -> set:
    """
    Filter search results based on publisher domain priority.

    Parameters
    ----------
    search_results : dict
        Dictionary of search results from Google or saved JSONs.
    domain_priority : str
        Priority of domain (High, Medium, Low) to select.
    page_num : int, optional
        If -1, use all pages; otherwise, use specific page number (default is -1).

    Returns
    -------
    filtered_search_links : set
        Set of URLs that match the desired domain priority.
    """
    file_path = os.path.join(DIR_PATH, 'data', f'publisher_priority_{domain_priority.lower()}.txt')
    with open(file_path, 'r') as f:
        selected_domains = f.read().split('\n')

    if page_num is None:
        sr = search_results
    else:
        sr = search_results['page_' + str(page_num + 1)]

    filtered_search_links = set()
    for results in sr.values():
        if 'image_results' not in results.keys():
            continue
        for res in results['image_results']:
            domain = res['link'].split('/')[2]
            domain = domain.replace('www.', '')
            if domain in selected_domains:
                filtered_search_links.add(res['link'])

    return filtered_search_links


def filter_search_results_by_query_sim(search_results: dict, top_k: int) -> list:
    """
    Filter search results based on their ranking (top-k) similarity to the query.

    Parameters
    ----------
    search_results : dict
        Dictionary containing Google search results.
    top_k : int
        Number of top items to select from each query result.

    Returns
    -------
    filtered_search_links : list
        List of filtered URLs.
    """
    filtered_search_links = set()
    for results in search_results.values():
        for i in range(min(top_k, len(results['items']))):
            filtered_search_links.add(results['items'][i]['link'])
    return list(filtered_search_links)


def article_crawler(article_urls: list, driver: webdriver) -> list:
    """
    Crawl web pages and extract article content.

    Parameters
    ----------
    article_urls : list
        List of URLs to crawl.
    driver : selenium.webdriver
        Selenium webdriver instance for fetching pages.

    Returns
    -------
    searched_articles : list
        List of dictionaries containing article data, including maintext,
        date of publication, URL, and language.
    """

    searched_articles = []

    articles_json = os.path.join(DIR_PATH, 'data', 'web_page_content.json')
    if not os.path.exists(articles_json):
        with open(articles_json, 'w') as f:
            json.dump({}, f)
    with open(articles_json, 'r') as f:
        saved_articles = json.load(f)

    for _, article_url in tqdm(enumerate(article_urls)):
        # Extract the content
        if article_url in saved_articles.keys():
            article = saved_articles[article_url]
        else:
            try:
                driver.get(article_url)
            except Exception as e:
                print('\t(fail to get ' + article_url + ')')
            soup = BeautifulSoup(driver.page_source, 'html.parser')
            article = NewsPlease.from_html(soup.prettify(), article_url).get_dict()

            saved_articles[article_url] = article
            with open(articles_json, 'w') as f:
                json.dump(saved_articles, f, sort_keys=True, default=str, indent=4)

        # Process the content
        if (
            article['maintext']
            and len(article['maintext'].split()) >= 100
            and article['date_publish']
            and article['language'] == 'en'
        ):
            # Remove the duplicate content
            flag = 0
            for searched_article in searched_articles:
                curr_article_time = datetime.strptime(str(article['date_publish']), '%Y-%m-%d %H:%M:%S')
                ref_article_time = datetime.strptime(str(searched_article['date_publish']), '%Y-%m-%d %H:%M:%S')
                if (
                    article['maintext'] in searched_article['maintext']
                    and (curr_article_time - ref_article_time).total_seconds() >= 0
                ):
                    flag = 1
                    break
                elif (
                    searched_article["maintext"] in article["maintext"]
                    and (ref_article_time - curr_article_time).total_seconds() >= 0
                ):
                    searched_articles.remove(searched_article)
                    searched_articles.append(article)
                    flag = 1
                    break
            if flag == 0:
                searched_articles.append(article)

    return searched_articles


def compute_unimodal_sims(news: dict, article: dict) -> dict:
    """
    Compute similarity between news text and article text using SentenceTransformer.

    Parameters
    ----------
    news : dict
        Dictionary with news data, must contain key 'TEXT'.
    article : dict
        Dictionary containing article data, must contain 'maintext' and 'url'.

    Returns
    -------
    articleUrl_textSim : dict
        Dictionary mapping article URL to similarity score.
    """

    def get_text_sim(model, text_1, text_2):
        embeds_1 = model.encode(text_1, convert_to_tensor=True).cpu()
        embeds_2 = model.encode(text_2, convert_to_tensor=True).cpu()
        return util.dot_score(embeds_1, embeds_2).numpy()[0][0]

    articleUrl_textSim = {article['url']: float(-1)}

    text_sim = get_text_sim(SentenceTransformer('msmarco-distilbert-base-tas-b'), news['TEXT'], article['maintext'])
    articleUrl_textSim[article['url']] = text_sim

    return articleUrl_textSim


def filter_search_results_by_unimodal_sim(
    list_of_articleUrl_textSim: list, searched_articles: list, max_num: int = 3, threshold: int = 90
) -> list:
    """
    Filter articles based on similarity scores with news content.

    Parameters
    ----------
    list_of_articleUrl_textSim : list
        List of dictionaries mapping article URL to similarity score.
    searched_articles : list
        List of article dictionaries previously crawled.
    max_num : int, optional
        Maximum number of articles to select (default is 3).
    threshold : float, optional
        Minimum similarity threshold to include article (default is 90).

    Returns
    -------
    filtered_searched_articles : list
        List of article dictionaries passing similarity threshold.
    """
    filtered_searched_links = set()

    article_urls = [
        article_url for articleUrl_textSim in list_of_articleUrl_textSim for article_url in articleUrl_textSim.keys()
    ]
    text_sims = [
        text_sim for articleUrl_textSim in list_of_articleUrl_textSim for text_sim in articleUrl_textSim.values()
    ]

    textSims_articleUrls = list(zip(text_sims, article_urls))
    textSims_articleUrls.sort(reverse=True)

    article_urls = [article_url for _, article_url in textSims_articleUrls]
    text_sims = [text_sim for text_sim, _ in textSims_articleUrls]

    x = min(len(text_sims), max_num)
    for idx in range(x):
        if text_sims[idx] >= threshold:
            filtered_searched_links.add(article_urls[idx])

    filtered_searched_articles = []
    for article in searched_articles:
        if article['url'] in filtered_searched_links:
            filtered_searched_articles.append(article)

    return filtered_searched_articles


def evidence_extraction(news: dict, article: dict, llm_key: str) -> tuple[list, list]:
    """
    Extract refute and context evidence from article for given news using LLM.

    Parameters
    ----------
    news : dict
        News dictionary containing 'CATEGORY' and 'TEXT'.
    article : dict
        Article dictionary containing 'maintext', 'date_publish', 'url', etc.
    llm_key : str
        API key for LLM (Gemini).

    Returns
    -------
    output : tuple
        Tuple of two lists: (refute_evidence, context_evidence)
    """
    output = ([], [])

    news_category = news['CATEGORY']
    news_text = news['TEXT']

    article_content = article['maintext']
    article_time = str(article['date_publish'])
    article_url = article['url']

    prompt = ''
    # Use the first max_chars characters
    article_content = article_content[:20000]

    prompt_evidence_path = os.path.join(DIR_PATH, 'data', 'prompt_evidence_extraction.txt')
    with open(prompt_evidence_path, 'r') as f:
        prompt_format = f.read()
    prompt = prompt_format.replace('[ARTICLE_CONTENT]', article_content)
    prompt = prompt.replace('[NEWS_CONTENT]', f'news category: {news_category}, content: {news_text}')

    evidence = gemini(llm_key, prompt)
    print("\t(sent 1 request to llm)")

    if 'explicit refutation' in evidence.lower() and 'implicit refutation' in evidence.lower():
        evidences = evidence.split('\n')
        for i, evidence in enumerate(evidences):
            if 'explicit refutation' in evidence.lower():
                er_loc = i
            elif 'implicit refutation' in evidence.lower():
                ce_loc = i
        refute_evidence, context_evidence = evidences[er_loc + 1 : ce_loc], evidences[ce_loc + 1 :]

        refute_evidence_2 = []
        for i, s in enumerate(refute_evidence):
            if 'NONE' in s or len(s) == 0 or (len(s) > 0 and s[0] != '-'):
                continue
            if article_time != '':
                subs = ' Reference: ' + article_url + ' published on ' + article_time
            else:
                subs = ' Reference: ' + article_url
            if len(s) > 1 and s[2] == "\"" and s[-1] == "\"":
                refute_evidence_2.append('- ' + s[3:-1] + subs)
            else:
                refute_evidence_2.append(s + subs)
        # print('---------refute_evidence---------')
        # print(refute_evidence_2)

        context_evidence_2 = []
        for i, s in enumerate(context_evidence):
            if 'NONE' in s or len(s) == 0 or (len(s) > 0 and s[0] != '-'):
                continue
            if article_time != '':
                subs = ' Reference: ' + article_url + ' published on ' + article_time
            else:
                subs = ' Reference: ' + article_url
            if len(s) > 1 and s[2] == "\"" and s[-1] == "\"":
                context_evidence_2.append('- ' + s[3:-1] + subs)
            else:
                context_evidence_2.append(s + subs)
        # print('---------context_evidence---------')
        # print(context_evidence_2)

        output = (refute_evidence_2, context_evidence_2)

    return output


def correction_generation(news: dict, list_of_evidences: list, list_of_refute_evidences: list, llm_key: str) -> str:
    """
    Generate correction for a news item using evidence and LLM.

    Parameters
    ----------
    news : dict
        Dictionary containing news information.
    list_of_evidences : list
        List of all extracted evidences.
    list_of_refute_evidences : list
        List of refutation evidences.
    llm_key : str
        API key for LLM (Gemini).

    Returns
    -------
    str
        Generated correction text.
    """
    no_retrieval_path = os.path.join(DIR_PATH, 'data', 'prompt_correction_generation_without_retrieval.txt')
    with_retrieval_path = os.path.join(DIR_PATH, 'data', 'prompt_correction_generation_with_retrieval.txt')
    if len(list_of_refute_evidences) == 0:
        with open(no_retrieval_path, 'r') as f:
            prompt = f.read()
    else:
        with open(with_retrieval_path, 'r') as f:
            prompt = f.read()
        prompt = prompt.replace('[RELEVANT_FACTS]', '\n'.join(list_of_evidences))

    news_category = news['CATEGORY']
    news_text = news['TEXT']

    prompt.replace('[NEWS_CONTENT]', f'news category: {news_category}, content: {news_text}')

    return gemini(llm_key, prompt)


def get_article_publish_date(article: dict) -> datetime:
    """
    Convert article's 'date_publish' field to a datetime object.

    Parameters
    ----------
    article : dict
        Dictionary containing key 'date_publish'.

    Returns
    -------
    datetime
        Parsed datetime object of publication date.
    """
    return datetime.strptime(str(article['date_publish']), "%Y-%m-%d %H:%M:%S")


if __name__ == '__main__':
    TEST_NEWS_ID = '1'
    data_file_id = '1QSZ8WRe2747lzueN5vkDP3ohbJavUNCH'
    download_url = f'https://drive.google.com/uc?export=download&id={data_file_id}'

    # Path of folder + path of api keys
    api_keys_path = os.path.join(DIR_PATH, 'data', 'api_keys.json')

    # Read the file
    data = pd.read_csv(download_url, dtype=str, encoding='latin-1')
    data = data.fillna('')

    instance = data[data['ID'] == TEST_NEWS_ID].to_dict('records')[0]

    # Load API keys
    with open(api_keys_path, 'r') as f:
        api_keys = json.load(f)

    llm_key = api_keys['gemini']
    serpapi_key = api_keys['SerpAPI']
    gsearch_key = api_keys['GoogleSearch']['Key']
    # llm_key = api_keys['HuggingFace']

    # Open a browser for article crawling
    options = Options()
    driver = webdriver.Firefox(options=options)
    driver.implicitly_wait(5)
    driver.set_page_load_timeout(10)

    # Set the number of processes = 5
    multiprocessing.set_start_method('spawn')
    pool = multiprocessing.Pool(processes=5)

    print('Start correcting news')

    print('Generate queries from misinformation...')
    instance['queries'] = query_generation(instance, llm_key)

    refute_evidences, context_evidences = set(), set()
    for domain_priority in ['High', 'Medium', 'Low']:
        print('Search web pages with ' + domain_priority + ' priority...')
        search_results = query_search(
            gsearch_key, api_keys['GoogleSearch'][domain_priority + '-Priority'], instance, domain_priority
        )

        print('Start selecting retrieved web pages...')

        # Filtered based on their similarities with the query
        filtered_search_links = filter_search_results_by_query_sim(search_results, 3)

        print('Extract retrieved web page content...')
        searched_articles = article_crawler(filtered_search_links, driver)
        if searched_articles == []:
            print('\t(no article found)')
            continue

        # Filtered based on their similarities with the misinfo content
        print('Compute the similarity between web page and misinformation content...')
        params = [(instance, article) for article in searched_articles]
        list_of_articleUrl_textSim = pool.starmap(compute_unimodal_sims, params)
        final_searched_articles = filter_search_results_by_unimodal_sim(list_of_articleUrl_textSim, searched_articles)
        if final_searched_articles == []:
            print('\t(no article qualified based on similarity)')
            continue

        print('Extract evidence from selected web pages...')
        params = [(instance, article, llm_key) for article in final_searched_articles]
        evidences = pool.starmap(evidence_extraction, params)

        for refute_evidence, context_evidence in evidences:
            refute_evidences = refute_evidences.union(set(refute_evidence))
            context_evidences = context_evidences.union(set(context_evidence))

        if len(refute_evidences) >= 3:
            print('\t(stop with sufficient refutations)')
            break

    if len(refute_evidences) == 0:
        print('\nExtend web search due to no refutations...')

        refute_evidences, context_evidences = set(), set()
        for domain_priority in ['High', 'Medium', 'Low']:
            print('Search web pages with ' + domain_priority + ' priority...')
            search_results = query_search(
                gsearch_key, api_keys['GoogleSearch'][domain_priority + '-Priority'], instance, domain_priority
            )

            print('Start selecting retrieved web pages...')

            # Filtered based on their similarities with the query
            filtered_search_links = filter_search_results_by_query_sim(search_results, 10)

            print('Extract retrieved web page content...')
            searched_articles = article_crawler(filtered_search_links, driver)
            if searched_articles == []:
                print('\t(no article found)')
                continue

            # Filtered based on their similarities with the misinfo content
            print('Compute the similarity between web page and misinformation content...')
            params = [(instance, article) for article in searched_articles]
            list_of_articleUrl_textSim = pool.starmap(compute_unimodal_sims, params)
            final_searched_articles = filter_search_results_by_unimodal_sim(
                list_of_articleUrl_textSim, searched_articles
            )
            if final_searched_articles == []:
                print('\t(no article qualified based on similarity)')
                continue

            print('Extract evidence from selected web pages...')
            params = [(instance, article, llm_key) for article in final_searched_articles]
            evidences = pool.starmap(evidence_extraction, params)

            for refute_evidence, context_evidence in evidences:
                refute_evidences = refute_evidences.union(set(refute_evidence))
                context_evidences = context_evidences.union(set(context_evidence))

            if len(refute_evidences) >= 3:
                print('\t(stop with sufficient refutations)')
                break

    refute_evidences = list(refute_evidences)
    context_evidences = list(context_evidences)

    instance['refute_evidence'] = refute_evidences
    instance['context_evidence'] = context_evidences

    evidences = refute_evidences + context_evidences

    print('Generate correction with ' + str(len(refute_evidences)) + ' refutations...')
    instance['correction'] = correction_generation(instance, evidences, refute_evidences, llm_key)

    output_path = os.path.join(DIR_PATH, 'data', 'output', f"{instance['ID']}.json")

    # Make sure that directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, 'w') as f:
        json.dump(instance, f, indent=4, sort_keys=True)

    print()
    print(instance['ID'])
    print(instance['correction'])

    driver.quit()
